DROP DATABASE IF EXISTS berties_books;
CREATE DATABASE berties_books;
USE berties_books;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

CREATE TABLE audit (
  id INT AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(255),
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);